env:
  browser: true
  es6: true
  node: true
extends:
  - plugin:vue/essential
  - airbnb-base
  - eslint:recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  parser: babel-eslint
  ecmaVersion: 2019
  sourceType: module
plugins:
  - vue
  - babel
rules: {
  "no-undef": "off",
  "no-shadow": "off",
  "babel/no-unused-expressions": 1,
  "no-unused-vars": "off",
  'no-param-reassign': [ 'error', {
    props: true,
    ignorePropertyModificationsFor: [
        'state'
    ]
  } ]
}
settings:
  import/extensions: [ ".js", ".vue" ]
  import/resolver: {
    "alias": {
      "extensions": [ ".vue" ]
    }
  }
